# Generated by Django 3.2.25 on 2025-03-03 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlistitem',
            old_name='Wishlist',
            new_name='wishlist',
        ),
    ]
