# Generated by Django 3.2.25 on 2025-03-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_category_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdf',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
