# Generated by Django 3.2.25 on 2025-03-15 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_pdf_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='pdf',
            name='thumbnail',
        ),
    ]
