# Generated by Django 3.2.25 on 2025-03-18 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_auto_20250316_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
