# Generated by Django 4.2 on 2025-03-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
