# Generated by Django 3.2.25 on 2025-03-18 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20250318_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
