# Generated by Django 4.2 on 2025-03-22 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20250318_1737'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReviewComment',
        ),
    ]
